version: '3.8'

services:
    redis:
        image: redis:5
    dev:
        image: meamyth/kraken-dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:5000
            - 9229:9229
        volumes:
            - ./kraken/.:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_CI_HOST: redis
            REDIS_CI_PORT: 6369
            PORT: 5000
        restart: unless-stopped
        depends_on:
        - redis
    prod:
        image: meamyth/kraken-prod
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3001:5000
        volumes:
            - ./kraken/.:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_CI_HOST: redis
            REDIS_CI_PORT: 6369
            PORT: 5000
        restart: unless-stopped
        depends_on:
        - redis