

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: redis-data
  resources:
    requests:
      storage: 100Mi